# Generated by Django 5.1 on 2024-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons/"),
        ),
    ]
