# Generated by Django 5.1.1 on 2024-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_seller_dailysalesreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysalesreport",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="dailysalesreport",
            unique_together={("date", "seller")},
        ),
    ]
