# Generated by Django 5.1 on 2024-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AddField(
            model_name="category",
            name="icon_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
